/* eslint-disable prettier/prettier */
export const DESHBOARD = "desboard";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const ALLUSERLIST = "ALLUSERLIST";
export const TOTALRIDERS_AND_DRIVERS = "TOTALRIDERS_AND_DRIVERS";
export const CHANGEUSERSTATUS = "CHANGEUSERSTATUS";
export const TRANSACTION_RIDELIST = "TRANSACTION_RIDELIST";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const TRANSACTION_SUMMARIES = "TRANSACTION_SUMMARIES";
export const ENTERUSERNAME = "ENTERUSERNAME";
export const ENTERUSERPASSWORD = "ENTERUSERPASSWORD";
export const TRANSACTION_HISTORIESLIST = "TRANSACTION_HISTORIESLIST";
export const MESSAGEDUMP = "MESSAGEDUMP";
export const VIEWTHREAD = "VIEWTHREAD";
export const PASSWRONG = "PASSWRONG";
export const TRANSACTION_HISTORIESLIST_RIDERS =
  "TRANSACTION_HISTORIESLIST_RIDERS";
export const ALL_RIDELIST = "ALL_RIDELIST";
export const GET_CAR_MODEL = "GET_CAR_MODEL";
export const ADD_CAR_BRAND = "ADD_CAR_BRAND";
export const ADD_CAR_MODEL = "ADD_CAR_MODEL";
export const DELETE_MODEL = "DELETE_MODEL";

export const ALL_LIVE = "ALL_LIVE";
export const ALL_PENDING = "ALL_PENDING";
export const ALL_CANCELLED = "ALL_CANCELLED";
export const AUTO_CANCELLED = "AUTO_CANCELLED";

export const GET_USER_DOCUMENT_LIST = "GET_USER_DOCUMENT_LIST";
export const ALLPENDINGDRIVERS = "ALLPENDINGDRIVERS";
export const GET_INSPECTION_DETAIL = "GET_INSPECTION_DETAIL";
export const ALLACTIVITYLOGS = "ALLACTIVITYLOGS";
export const GET_RIDES = "GET_RIDES";
export const RIDES_DETAILS = "RIDES_DETAILS";
export const RIDER_DETAILS = "RIDER_DETAILS";
